# Generated by Django 3.2.7 on 2021-09-15 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Measurement', '0002_auto_20210914_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
